const core = require('@actions/core');
const github = require('@actions/github');
const { generateReleaseNotes } = require('./src/llm');
const { fetchCommitsSinceLastRelease, fetchPullRequestsSinceLastRelease } = require('./src/github');
const { validateLicense, broadcastIfPro } = require('./src/pro');

// Free-tier limits — designed to be useful but drive upgrades
const FREE_TIER = {
  MAX_COMMITS: 25,              // Free: last 25 commits only
  MAX_PRS: 10,                  // Free: last 10 PRs only
  MAX_NOTES_WORDS: 150,         // Free: short summary, no categories
  LANGUAGE: 'en',               // Free: English only
  TONE: 'professional',         // Free: locked tone
  MODEL: 'openrouter/auto',     // Free: cheap model
  BRANDING: `\n\n---\n📝 _Generated by [Release Notes AI](https://github.com/aura-fyll/release-notes-ai). Upgrade to Pro for full structured notes + Slack/Discord broadcast — https://pol.sh/r/your-product_`,
  UPGRADE_LINK: 'https://pol.sh/r/your-product',
};

async function run() {
  try {
    const token = core.getInput('github_token', { required: true });
    const openrouterKey = core.getInput('openrouter_api_key', { required: true });
    const modelInput = core.getInput('openrouter_model') || '';
    const licenseKey = core.getInput('pro_license_key') || '';
    const composioKey = core.getInput('composio_api_key') || '';
    const channels = (core.getInput('broadcast_channels') || 'slack').split(',').map(s => s.trim());
    const languageInput = core.getInput('language') || 'en';
    const toneInput = core.getInput('tone') || 'professional';

    const ctx = github.context;
    if (ctx.eventName !== 'release' || ctx.payload.action !== 'published') {
      core.info(`⏭️  Event is '${ctx.eventName}/${ctx.payload.action}'. Only 'release/published' triggers notes. Exiting.`);
      return;
    }
    const release = ctx.payload.release;
    if (!release) {
      core.setFailed('No release object found in payload.');
      return;
    }

    const octokit = github.getOctokit(token);
    const { owner, repo } = ctx.repo;

    // ─────────────────────────────────────────────────────────────
    // License check — determines tier
    // ─────────────────────────────────────────────────────────────
    let isPro = false;
    if (licenseKey) {
      isPro = await validateLicense(licenseKey);
      if (isPro) {
        core.info('🔑 Pro license valid — full features unlocked.');
      } else {
        core.warning('⚠️  Invalid or expired Pro license key. Falling back to free tier.');
      }
    }

    const tier = isPro ? 'PRO' : 'FREE';
    core.info(`📝 [${tier}] Generating release notes for ${owner}/${repo} @ ${release.tag_name}`);

    // ─────────────────────────────────────────────────────────────
    // Apply tier limits
    // ─────────────────────────────────────────────────────────────
    const model = isPro
      ? (modelInput || 'anthropic/claude-3.5-sonnet')
      : FREE_TIER.MODEL; // Free: always use cheap model regardless of input

    const language = isPro
      ? languageInput
      : FREE_TIER.LANGUAGE; // Free: English only

    const tone = isPro
      ? toneInput
      : FREE_TIER.TONE; // Free: professional only

    // ─────────────────────────────────────────────────────────────
    // Gather commits + PRs
    // ─────────────────────────────────────────────────────────────
    let commits = await fetchCommitsSinceLastRelease(octokit, owner, repo, release.tag_name);
    let prs = await fetchPullRequestsSinceLastRelease(octokit, owner, repo, release.tag_name);

    let truncatedNotice = '';
    if (!isPro) {
      const totalCommits = commits.length;
      const totalPrs = prs.length;
      if (commits.length > FREE_TIER.MAX_COMMITS) {
        commits = commits.slice(0, FREE_TIER.MAX_COMMITS);
        truncatedNotice = `_(Free tier: showing first ${FREE_TIER.MAX_COMMITS} of ${totalCommits} commits. Upgrade to Pro for full history.)_`;
      }
      if (prs.length > FREE_TIER.MAX_PRS) {
        prs = prs.slice(0, FREE_TIER.MAX_PRS);
        if (!truncatedNotice) {
          truncatedNotice = `_(Free tier: showing first ${FREE_TIER.MAX_PRS} of ${totalPrs} PRs. Upgrade to Pro for full history.)_`;
        }
      }
    }

    core.info(`   Using ${commits.length} commits and ${prs.length} PRs (${tier}).`);

    if (commits.length === 0 && prs.length === 0) {
      core.info('ℹ️  No new commits or PRs since last release. Skipping generation.');
      return;
    }

    // ─────────────────────────────────────────────────────────────
    // Generate notes (different prompt for free vs Pro)
    // ─────────────────────────────────────────────────────────────
    const notes = await generateReleaseNotes({
      openrouterKey,
      model,
      owner,
      repo,
      tag: release.tag_name,
      commits,
      prs,
      language,
      tone,
      isPro,
      maxWords: isPro ? null : FREE_TIER.MAX_NOTES_WORDS,
    });

    // Apply free-tier post-processing: branding + truncation notice
    let finalBody = notes;
    if (!isPro) {
      if (truncatedNotice) {
        finalBody = `${notes}\n\n${truncatedNotice}`;
      }
      finalBody += FREE_TIER.BRANDING;
    }

    // ─────────────────────────────────────────────────────────────
    // Update the GitHub release
    // ─────────────────────────────────────────────────────────────
    await octokit.rest.repos.updateRelease({
      owner,
      repo,
      release_id: release.id,
      body: finalBody,
    });
    core.info('✅ Release notes updated on GitHub.');

    // ─────────────────────────────────────────────────────────────
    // Pro tier: broadcast via Composio
    // ─────────────────────────────────────────────────────────────
    if (isPro) {
      if (!composioKey) {
        core.warning('⚠️  Pro license present but COMPOSIO_API_KEY is empty. Skipping broadcast.');
        return;
      }
      core.info('📡 Broadcasting via Composio...');
      await broadcastIfPro({
        composioKey,
        channels,
        owner,
        repo,
        tag: release.tag_name,
        releaseUrl: release.html_url,
        notes,
      });
      core.info('📡 Broadcast complete.');
    } else {
      core.info(`ℹ️  Free tier only. Upgrade to Pro: ${FREE_TIER.UPGRADE_LINK}`);
    }
  } catch (err) {
    core.setFailed(`Action failed: ${err.message}`);
    if (err.stack) core.debug(err.stack);
  }
}

run();
